common/models/food.py
# coding: utf-8
from common.models import BaseModel
from application import db
from application import app

class Food(BaseModel):
    __tablename__ = 'food'

    id = db.Column(db.Integer, primary_key=True)
    cat_id = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='分类id')
    name = db.Column(db.String(100), nullable=False, server_default=db.FetchedValue(), comment='美食名称')
    price = db.Column(db.Numeric(10, 2), nullable=False, server_default=db.FetchedValue(), comment='售卖金额')
    main_image = db.Column(db.String(100), nullable=False, server_default=db.FetchedValue(), comment='主图')
    summary = db.Column(db.String(10000), nullable=False, server_default=db.FetchedValue(), comment='描述')
    stock = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='库存量')
    tags = db.Column(db.String(200), nullable=False, server_default=db.FetchedValue(), comment='tag关键字，以","连接')
    status = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='状态 1：正常 0：删除')
    month_count = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='月销售数量')
    total_count = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='总销售量')
    view_count = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='总浏览次数')
    comment_count = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='总评论量')
    updated_time = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), comment='最后更新时间')
    created_time = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), comment='最后插入时间')


class FoodCat(BaseModel):
    __tablename__ = 'food_cat'

    id = db.Column(db.Integer, primary_key=True, unique=True)
    name = db.Column(db.String(50), nullable=False, server_default=db.FetchedValue(), comment='类别名称')
    weight = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='权重')
    status = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='状态 1：正常 0：已删除')
    updated_time = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), comment='最后一次更新时间')
    created_time = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), comment='插入时间')

    @property
    def status_desc(self):
        return app.config['STATUS_MAPPING'][str(self.status)]


class FoodSaleChangeLog(BaseModel):
    __tablename__ = 'food_sale_change_log'

    id = db.Column(db.Integer, primary_key=True)
    food_id = db.Column(db.Integer, nullable=False, index=True, server_default=db.FetchedValue(), comment='商品id')
    quantity = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='售卖数量')
    price = db.Column(db.Numeric(10, 2), nullable=False, server_default=db.FetchedValue(), comment='售卖金额')
    member_id = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='会员id')
    created_time = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), comment='售卖时间')


class FoodStockChangeLog(BaseModel):
    __tablename__ = 'food_stock_change_log'

    id = db.Column(db.Integer, primary_key=True)
    food_id = db.Column(db.Integer, nullable=False, index=True, comment='商品id')
    unit = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='变更多少')
    total_stock = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='变更之后总量')
    note = db.Column(db.String(100), nullable=False, server_default=db.FetchedValue(), comment='备注字段')
    created_time = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), comment='插入时间')


class WxShareHistory(BaseModel):
    __tablename__ = 'wx_share_history'

    id = db.Column(db.Integer, primary_key=True)
    member_id = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), comment='会员id')
    share_url = db.Column(db.String(200), nullable=False, server_default=db.FetchedValue(), comment='分享的页面url')
    created_time = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), comment='创建时间')

web/templates/food/cat.html
{% extends "common/layout_main.html" %}
{% block content %}
    {% include 'common/tab_food.html' %}
    <div class="row">
        <div class="col-lg-12">
            <form class="form-inline wrap_search">
                <div class="row  m-t p-w-m">
                    {% include 'common/search_status.html' %}
                </div>
                <hr>
                <div class="row">
                    <div class="col-lg-12">
                        <a class="btn btn-w-m btn-outline btn-primary pull-right"
                           href="{{ buildUrl('/food/cat-set') }}">
                            <i class="fa fa-plus"></i>分类
                        </a>
                    </div>
                </div>
            </form>
            <table class="table table-bordered m-t">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>分类名称</th>
                    <th>状态</th>
                    <th>权重</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% if food_cat_list %}
                    {% for food_cat in food_cat_list %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ food_cat.name }}</td>
                            <td>{{ food_cat.status_desc }}</td>
                            <td>{{ food_cat.weight }}</td>
                            <td>
                                {% if food_cat.status == 1 %}
                                    <a class="m-l" href="{{ buildUrl('/food/cat-set') }}?id={{ food_cat.id }}">
                                        <i class="fa fa-edit fa-lg"></i>
                                    </a>
                                {% endif %}
                                {% if food_cat.status == 1 %}
                                    <a class="m-l remove" href="javascript:void(0);" data="{{ food_cat.id }}">
                                        <i class="fa fa-trash fa-lg"></i>
                                    </a>
                                {% else %}
                                    <a class="m-l recover" href="javascript:void(0);" data="{{ food_cat.id }}">
                                        <i class="fa fa-refresh fa-lg"></i>
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="5">暂无数据</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{{ buildStaticUrl('/js/food/cat_ops.js') }}"></script>
{% endblock %}

web/templates/food/cat_set.html
{% extends "common/layout_main.html" %}
{% block content %}
    {% include 'common/tab_food.html' %}
    <div class="row m-t  wrap_cat_set">
        <div class="col-lg-12">
            <h2 class="text-center">分类设置</h2>
            <div class="form-horizontal m-t m-b">
                <div class="form-group">
                    <label class="col-lg-2 control-label">分类名称:</label>
                    <div class="col-lg-10">
                        <input type="text" name="cat_name" class="form-control" placeholder="请输入分类名称"
                               value="{{ food_cat.name }}">
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">权重:</label>
                    <div class="col-lg-10">
                        <input type="text" name="weight" class="form-control" placeholder="请输入分类权重"
                               {% if food_cat %}value="{{ food_cat.weight }}"{% else %} value="1"{% endif %}>
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group">
                    <div class="col-lg-4 col-lg-offset-2">
                        <input type="hidden" name="id" value="{{ food_cat.id }}">
                        <button class="btn btn-w-m btn-outline btn-primary save">保存</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{{ buildStaticUrl('/js/food/food_cat.js') }}"></script>
{% endblock %}

web/templates/food/index.html
{% extends "common/layout_main.html" %}
{% block content %}
    {% include 'common/tab_food.html' %}
    <div class="row">
        <div class="col-lg-12">
            <form class="form-inline wrap_search">
                <div class="row  m-t p-w-m">
                    {% include 'common/search_status.html' %}
                    <div class="form-group">
                        <select name="cat_id" class="form-control inline">
                            <option value="0">请选择分类</option>
                            {% for key,value in cat_mapping.items() %}
                                <option value="{{ key }}" {% if key|string==search_val.cat_id %}selected {% endif %}>
                                    {{ value.name }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" name="mix_kw" autocomplete="off" placeholder="请输入关键字" class="form-control" value="">
                            <span class="input-group-btn">
                            <button type="button" class="btn  btn-primary search">
                                <i class="fa fa-search"></i>搜索
                            </button>
                        </span>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-lg-12">
                        <a class="btn btn-w-m btn-outline btn-primary pull-right" href="{{ buildUrl('/food/set') }}">
                            <i class="fa fa-plus"></i>美食
                        </a>
                    </div>
                </div>

            </form>
            <table class="table table-bordered m-t">
                <thead>
                <tr>
                    <th>美食名</th>
                    <th>分类</th>
                    <th>价格</th>
                    <th>库存</th>
                    <th>标签</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% if pagination.items %}
                    {% for food in pagination.items %}
                        <tr>
                            <td>{{ food.name }}</td>
                            <td>{{ cat_mapping[food.cat_id].name }}</td>
                            <td>{{ food.price }}</td>
                            <td>{{ food.stock }}</td>
                            <td>{{ food.tags }}</td>
                            <td>
                                {% if food.status==1 %}
                                    <a href="{{ buildUrl('/food/info') }}?id={{ food.id }}">
                                        <i class="fa fa-eye fa-lg"></i>
                                    </a>
                                    <a class="m-l" href="{{ buildUrl('/food/set') }}?id={{ food.id }}">
                                        <i class="fa fa-edit fa-lg"></i>
                                    </a>
                                {% endif %}
                                {% if food.status == 1 %}
                                    <a class="m-l remove" href="javascript:void(0);" data="{{ food.id }}">
                                        <i class="fa fa-trash fa-lg"></i>
                                    </a>
                                {% else %}
                                    <a class="m-l recover" href="javascript:void(0);" data="{{ food.id }}">
                                        <i class="fa fa-refresh fa-lg"></i>
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <td colspan="6">暂无数据</td>
                {% endif %}
                </tbody>
            </table>
            {% include 'common/pagenation.html' %}
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{{ buildStaticUrl('/js/food/food_ops.js') }}"></script>
{% endblock %}

web/templates/food/info.html
{% extends "common/layout_main.html" %}
{% block content %}
    {% include 'common/tab_food.html' %}
    <style type="text/css">
        .wrap_info img {
            width: 70%;
        }
    </style>
    <div class="row m-t wrap_info">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-12">
                    <div class="m-b-md">
                        <a class="btn btn-outline btn-primary pull-right"
                           href="{{ buildUrl('/food/set') }}?id={{ food_info.id }}">
                            <i class="fa fa-pencil"></i>编辑
                        </a>
                        <h2>美食信息</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <p class="m-t">美食名：{{ food_info.name }}</p>
                    <p>售价：{{ food_info.price }}</p>
                    <p>库存总量：{{ food_info.stock }}</p>
                    <p>图书标签：{{ food_info.tags }}</p>
                    <p>封面图：<img src="{{ buildImageUrl(food_info.main_image) }}" style="width: 50px;height: 50px;"></p>
                    <p>描述：</p>
                    <p>{{ food_info.summary |safe }}</p>
                </div>
            </div>
            <div class="row m-t">
                <div class="col-lg-12">
                    <div class="panel blank-panel">
                        <div class="panel-heading">
                            <div class="panel-options">
                                <ul class="nav nav-tabs">
                                    <li class="active">
                                        <a href="#tab-1" data-toggle="tab" aria-expanded="false">销售历史</a>
                                    </li>
                                    <li>
                                        <a href="#tab-2" data-toggle="tab" aria-expanded="true">库存变更</a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="panel-body">
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab-1">
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>会员名称</th>
                                            <th>购买数量</th>
                                            <th>购买价格</th>
                                            <th>订单状态</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% if pay_order_items %}
                                            {% for item in pay_order_items %}
                                                <tr>
                                                    <td>{{ member_order_mapping[item.member_id].nickname }}</td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.price }}</td>
                                                    <td>{{ item.status_desc }}</td>
                                                </tr>
                                            {% endfor %}
                                        {% else %}
                                            <tr>
                                                <td colspan="4">暂无销售记录</td>
                                            </tr>
                                        {% endif %}
                                        </tbody>
                                    </table>
                                </div>
                                <div class="tab-pane" id="tab-2">
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>变更</th>
                                            <th>备注</th>
                                            <th>时间</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% if  stock_list %}
                                            {% for stock in stock_list %}
                                                <tr>
                                                    <td>{{ stock.unit }}</td>
                                                    <td>{{ stock.note }}</td>
                                                    <td>{{ stock.created_time }}</td>
                                                </tr>
                                            {% endfor %}
                                        {% else %}
                                            <td colspan="3">暂无数据</td>
                                        {% endif %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

web/templates/food/set.html
{% extends "common/layout_main.html" %}
{% block content %}
    {% include 'common/tab_food.html' %}
    <div class="row mg-t20 wrap_food_set" style="">
        <div class="col-lg-12" style="">
            <h2 class="text-center">设置</h2>
            <div class="form-horizontal m-t" style="">
                <div class="form-group">
                    <label class="col-lg-2 control-label">分类:</label>
                    <div class="col-lg-10">
                        <select name="cat_id" class="form-control select2-hidden-accessible" tabindex="-1"
                                aria-hidden="true">
                            <option value="0">请选择分类</option>
                            {% for key,value in cat_mapping.items() %}
                                <option value="{{ key }}" {% if food.cat_id == key %}selected{% endif %}>{{ value.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">名称:</label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" placeholder="请输入名称" name="name" value="{{ food.name }}">
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">价格:</label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" placeholder="请输入售价" name="price"
                               value="{{ food.price }}">
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">封面图:</label>
                    <div class="col-lg-10">
                        <form class="upload_pic_wrap" target="upload_file" enctype="multipart/form-data" method="POST"
                              action="{{ buildUrl('/upload/pic') }}">
                            <div class="upload_wrap pull-left">
                                <i class="fa fa-upload fa-2x"></i>
                                <input type="file" name="pic" accept="image/png, image/jpeg, image/jpg,image/gif">
                            </div>
                            {% if food %}
                                <span class="pic-each">
                                    <img src="{{ buildImageUrl(food.main_image) }}"/>
                                    <span class="fa fa-times-circle del del_image" data="{{ food.main_image }}"></span>
                                 </span>
                            {% endif %}
                        </form>
                    </div>
                    <iframe name="upload_file" style="display: none;"></iframe>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group" style="">
                    <label class="col-lg-2 control-label">描述:</label>
                    <div class="col-lg-10">
                        <!-- 加载编辑器的容器 -->
                        {#                        <script id="container" name="content" type="text/plain" style="height: 300px;width: 630px;"></script>#}
                        <textarea id="container" name="summary"
                                  style="height: 300px;width: 630px;">{{ food.summary }}</textarea>
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">库存:</label>
                    <div class="col-lg-2">
                        <input type="text" name="stock" class="form-control" value="{{ food.stock }}">
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">标签:</label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" name="tags" value="{{ food.tags }}">
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group">
                    <div class="col-lg-4 col-lg-offset-2">
                        <input type="hidden" name="id" value="{{ food.id }}">
                        <button class="btn btn-w-m btn-outline btn-primary save">保存</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{{ buildStaticUrl('/plugins/select2/select2.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ buildStaticUrl('/plugins/tagsinput/jquery.tagsinput.min.css') }}">
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{{ buildStaticUrl('/plugins/ueditor/ueditor.config.js') }}"></script>
    <script type="text/javascript" src="{{ buildStaticUrl('/plugins/ueditor/ueditor.all.min.js') }}"></script>
    <script type="text/javascript" src="{{ buildStaticUrl('/plugins/ueditor/lang/zh-cn/zh-cn.js') }}"></script>

    <script type="text/javascript" src="{{ buildStaticUrl('/plugins/select2/pinyin.core.js') }}"></script>
    <script type="text/javascript" src="{{ buildStaticUrl('/plugins/select2/select2.pinyin.js') }}"></script>
    <script type="text/javascript" src="{{ buildStaticUrl('/plugins/select2/zh-CN.js') }}"></script>

    <script type="text/javascript" src="{{ buildStaticUrl('/plugins/tagsinput/jquery.tagsinput.min.js') }}"></script>

    <script src="{{ buildStaticUrl('/js/food/food_set.js') }}"></script>

{% endblock %}